Connection Sendgrid V4
lowdefy/lowdefy pull request #1074
Opened 2022-01-25 21:18 UTC by correiarmjoao

### What are the changes and their implications?

Fixed plugin structure to work with version 4.

## Checklist

- [x] Pull request is made to the "develop" branch
- [ ] Tests added
- [ ] Documentation added/updated
- [x] Code has been formatted with Prettier
- [ ] Edits from maintainers are allowed

2022-01-25 21:23 UTC, correiarmjoao commented
<img width="927" alt="SendGrid" src="https://user-images.githubusercontent.com/29627639/151061881-53a5a712-12b1-4ab2-950c-78a76c94d22d.png">

2022-01-26 07:25 UTC, SamTolmay submitted a review, later dismissed

2022-01-26 10:39 UTC, Gervwyk requested changes
Hi @correiarmjoao 
Please add license comments to all new files, (schema.js)

2022-01-31 12:28 UTC, SamTolmay approved these changes

2022-02-01 07:24 UTC, SamTolmay approved these changes

2022-02-01 10:06 UTC, merged