Allow onClick to be passed down to Link component.
lowdefy/lowdefy pull request #1474
Opened 2023-01-19 07:31 UTC by StephanieJKS

### What are the changes and their implications?
This PR allows an onClick method to be passed down to the Link component which will be executed when the link is clicked.

## Checklist

- [ ] Pull request is made to the "develop" branch
- [ ] Tests added
- [ ] Documentation added/updated
- [ ] Code has been formatted with Prettier
- [ ] Edits from maintainers are allowed

2023-01-19 13:59 UTC, Gervwyk approved these changes

2023-01-19 14:00 UTC, Gervwyk approved these changes

2023-01-19 14:01 UTC, Gervwyk requested changes
Please also update the schema.json for Anchor.

2023-01-31 08:46 UTC, SamTolmay approved these changes

2023-01-31 08:49 UTC, merged