Change case operator
lowdefy/lowdefy pull request #702
Opened 2021-07-22 07:18 UTC by JohannMoller

Closes: #631

### What are the changes and their implications?
This pull request adds a new `_change_case` operator using the [`change-case`](https://www.npmjs.com/package/change-case) package to transform a string between cases using a list of methods.

## Checklist

- [x] Pull request is made to the "develop" branch
- [x] Tests added
- [ ] Documentation added/updated

2021-07-22 07:38 UTC, SamTolmay commented on packages/operators/src/common/change_case.js
> +
Maybe rather do `([key, val]) =>` instead

2021-07-22 07:41 UTC, SamTolmay commented on packages/operators/test/common/change_case.test.js
> +test('_change_case.capitalCase on: object, options: {}', () => {
Add that convertValue is default true in test name

2021-07-22 08:06 UTC, Gervwyk approved these changes

2021-07-22 12:52 UTC, Gervwyk approved these changes

2021-07-22 13:16 UTC, JohannMoller commented
I didn't add examples of change-case's own options, only our `convertKeys` and `convertValues` options. Is that okay?

2021-07-22 13:34 UTC, Gervwyk requested changes

2021-07-22 13:34 UTC, Gervwyk commented on packages/docs/operators/_change_case.yaml
> +      The `_change_case` operator uses the [`change-case`](https://www.npmjs.com/package/change-case) package to transform an input between camelCase, PascalCase, Capital Case, snake_case, param-case
Please add a list of all possible cases instead of etc.

2021-07-22 13:34 UTC, Gervwyk commented on packages/docs/operators/_change_case.yaml
> +        - `splitRegexp`: The regular expression used to split `on` into word segments.
Can we add tests for these regex options?

When passing in reg expressions to operators you need to test for the option and create a Regex from the input string to pass to the lib. 

Have a look at the implementation for `_regex`.

2021-07-23 14:43 UTC, SamTolmay commented on packages/docs/operators/_change_case.yaml
> +          foo: 'bar'
Add option here

2021-07-23 14:44 UTC, SamTolmay commented on packages/docs/operators/_change_case.yaml
> +          foo: 'bar'
Same as above

2021-07-25 09:30 UTC, Gervwyk approved these changes

2021-07-25 09:31 UTC, merged