Actions async option
lowdefy/lowdefy pull request #749
Opened 2021-08-13 14:20 UTC by JohannMoller

Closes: #745 

### What are the changes and their implications?
The pull request adds an `async` option to actions which will allow them to be executed asynchronously in an event's action chain. 

Note: if this action throws an error, the event chain still completes successfully.

## Checklist

- [x] Pull request is made to the "develop" branch
- [x] Tests added
- [x] Documentation added/updated
- [x] Code has been formatted with Prettier
- [x] Edits from maintainers are allowed

2021-08-13 14:53 UTC, SamTolmay approved these changes

2021-08-16 11:58 UTC, Gervwyk requested changes

2021-08-16 11:58 UTC, Gervwyk commented on packages/engine/src/Actions.js
> +          });
@SamTolmay Should we not set
```js
this.callAsyncAction({
            action,
            arrayIndices,
            block,
            event,
            index,
            responses,
          }).then( (response) => { responses[action.id] = response; });
```
we need to log the action to the responses object.

2021-08-16 12:36 UTC, Gervwyk approved these changes

2021-08-16 13:25 UTC, merged